config/routes.rb
Rails.application.routes.draw do

  resources :recipes do 
    resources :comments
  end
  devise_for :users

  authenticated :user do
    root 'recipes#index', as: :authenticated_root
  end

  #get 'recipes',to: "recipes#index"
  root 'home#index'
  get 'user/:id', to: 'home#profile'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :update, Recipe do |recipe|
        recipe.user ==user
    end

    can :destroy, Recipe do |recipe|
        recipe.user ==user
    end


    can :create, Recipe
    can :read, :all

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates_presence_of :content
  validates_presence_of :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :recipe_styles
  has_many :styles, through: :recipe_styles
  mount_uploader :image, ImageUploader
  validates_presence_of :name
   validates_presence_of :user_id
   default_scope{order('created_at desc')}

  validate :user_id
  validate :image_size
  
#friendly_id
  extend FriendlyId
  friendly_id :name, use: :slugged


  private
  def image_size
    if image.size > 2.megabytes
      errors.add(:image, " File should be less than 2MB")
    end
  end
end

app/models/recipe_style.rb
class RecipeStyle < ApplicationRecord
  belongs_to :recipe
  belongs_to :style
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
      respond_to do |format|
        format.json { head :forbidden, content_type: 'text/html' }
        format.html { redirect_to main_app.root_url, notice: exception.message }
        format.js   { head :forbidden, content_type: 'text/html' }
      end
    end

     def after_sign_in_path_for(resource)
        request.env['omniauth.origin'] || stored_location_for(resource) || recipes_path
     end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
   
  def create
    @recipe = Recipe.friendly.find(params[:recipe_id])
    @comment = @recipe.comments.create(comment_params)
    @comment.user = current_user
    @comment.save!
    respond_to do |format|
      format.html {redirect_to recipe_path(@recipe)}
      format.js
      
    end
    
  end
 
  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recipes = Recipe.all.limit(1).order('created_at desc')
  end

  def profile
    if User.find_by_name(params[:id])
    @username = params[:id]
   else
    redirect_to root_path, notice: "User Not Found"
   end

    @recipes = Recipe.where("user_id = ?", User.find_by_name(params[:id])).order("created_at desc")
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user! , except:[:index, :show]
   before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource param_method: :my_sanitizer

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.friendly.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(my_sanitizer)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
     authorize! :update, @recipe
    respond_to do |format|
      if @recipe.update(my_sanitizer)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
     authorize! :destroy, @recipe
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_sanitizer
      params.require(:recipe).permit(:name, :summary, :description, :ingredients, :image, :user_id ,style_ids:[],)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_comment.html.erb
<div class="card my-2">
  <div class="card-block">
    <%= comment.user.name %> wrote: <%= comment.content %> <br>
    <small>about <%= time_ago_in_words(comment.created_at) %> ago</small>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@recipe, @recipe.comments.build],remote: true) do |f| %>
  <p>
    <%= f.input :content ,placeholder: "write a comment..."%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comments-section').append("<%= j render @recipe.comments %>");
$('#comment_content').val("")

app/views/home/index.html.erb
<header>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
         
            <ol class="carousel-indicators"> 
            <% @recipes.each do |recipe| %>
                <li data-target="#carouselExampleIndicators" data-slide-to="<%=recipe%>"></li>
                  <%end%>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
           <% @recipes.each do |recipe| %>
                <div class="carousel-item active" style="background-image: url('http://placehold.it/1900x1080/1abc9c/fff')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3><%=link_to recipe.name,recipe_path(recipe) %></h3>
                        <p><%=recipe.summary%>.</p>
                    </div>
                </div>
                  <%end%>
                   
                <!-- Slide Two - Set the background image for this slide in the line below -->
                <!-- <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080/1abc9c/fff')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Second Slide</h3>
                        <p>This is a description for the second slide.</p>
                    </div>
                </div> -->
                <!-- Slide Three - Set the background image for this slide in the line below -->
                <!-- <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080/e67e22/fff')">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>Third Slide</h3>
                        <p>This is a description for the third slide.</p>
                    </div>
                </div> -->
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
          
        </div>
</header>

<section class="featured d-flex flex-column justify-content-center py-6">
    <div class="p-2">RECIPE OF THE WEEK</div>
    <div class="book">
    <%= image_tag('book-promo.png', size: '220x220', class: "align-self-center p-3")%>
</div>
    <div class="btn btn-secondary px-5 align-self-center p-3">VIEW</div>
</section>

<section class="inspired py-0">

    
</section>

app/views/home/profile.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3"><%=@username%>'s Recipes</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>

<div class="col">
  <% @recipes.each do |recipe|%>
  <div class="card my-2">
      <div class="card-block ">
        <h4><%= link_to recipe.name,recipe_path(recipe)%></h4>
        <%=recipe.summary %> <br>
        <em><%=recipe.user.name %></em> <br> 
        <small> Created <%=recipe.created_at.to_formatted_s(:time) %></small>
      </div>
    </div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmbazoniaRecipes</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container-fluid"> <%= render 'shared/navbar' %>
      <%= yield %>
        
      </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name%>
    <%= f.input :summary %>
    <%= f.input :ingredients %>
    <%= f.input :description %>
    <%= image_tag(@recipe.image.thumb.url) if @recipe.image? %>
    <%= f.input :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-inputs">
     <%= f.association :styles, label: "Contains", input_html: { id: 'selectized'} ,placeholder: "select styles......" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script type="text/javascript">
  $('#recipe_image').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5){
      alert('Maxinum file size is 2 MB');
    }
  });
</script>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>


    <% @recipes.each do |recipe| %>
       <p> <%= link_to recipe do %>
              <%= image_tag recipe.image , size: "400x250" %> 
            <%end%>
             <br> 
         <%= link_to recipe.name, recipe_path(recipe) %> <br>
         <%= recipe.summary %> <br>
         <small>Created_by <%= recipe.user.name %></small>
        </p>
        <%end%>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', recipes_path %>
<p>
  <strong>Image:</strong>
  <%= image_tag @recipe.image ,size: "600x350"%>
</p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @recipe.summary %>
</p>
<p>
<strong>Contains</strong>
   <small> <%= render @recipe.styles if @recipe.styles.present?%></small>
    </p>

    <p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>
<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<% if can? :update, @recipe %>
  <%= link_to 'Edit', edit_recipe_path(@recipe) %> |<%end%>
<% if can? :destroy, @recipe %>
<%= link_to "Delete this Recipe", recipe_path(@recipe),
                                    method: :delete,
                                    data: { confirm: "Are you sure you want to delete this Recipe?"} %> <br>
<%end%>



<%= link_to 'Comments','#', id: "comments-link"%>(<%= @recipe.comments.count%>)


    <div id="comments-section">
       <%= render @recipe.comments %>
    </div>
    <% if user_signed_in? %>
       <%= render 'comments/form'%>
       <%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%=link_to 'Ambazonian Recipe', root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'New Recipe ',new_recipe_path, class: "nav-link" %>
      </li>
      <%end%>
    </ul>
    <ul class="navbar-nav ml-2">
    <% if !user_signed_in? %>
      <li class="nav-item">
        <%=link_to 'Log In', new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%=link_to 'Register', new_user_registration_path, class: "nav-link"%>
      </li>
      <%else%>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/user/<%=current_user.name%>">Profile</a>
           <div class="dropdown-divider"></div>
          <%=link_to 'Settings', edit_user_registration_path, class: "dropdown-item"  %>
           <div class="dropdown-divider"></div>
          <%=link_to 'Help', '', class: "dropdown-item"  %>
           <div class="dropdown-divider"></div>
           <%=link_to 'Log Out', destroy_user_session_path, class: "dropdown-item" ,method: :delete %>
        </div>
      </li>
      <%end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/styles/_style.html.erb
 <%= link_to style.name %>